image: docker:latest

stages:
  - build

variables:
  PYTHON_VERSION: "3.7"
  DOCKER_IMAGE: "hello:gitlab-$CI_COMMIT_SHORT_SHA"

builder:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker tag $DOCKER_IMAGE $CI_REGISTRY_IMAGE/$DOCKER_IMAGE
    - docker push $CI_REGISTRY_IMAGE/$DOCKER_IMAGE